name: Release

on:
  push

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: bank-vaults/bank-vaults/.github/workflows/artifacts.yaml@main 
    with:
      publish: true
      release: true
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
